### ISSUE TITLE
感谢大佬开发的插件，我来交作业

### ISSUE THREAD

**Issue by miaoziguan** [TarsLab/obsidian-ai-zhipu#1]
<img width="734" alt="image" src="https://github.com/TarsLab/obsidian-ai-zhipu/assets/115944923/32b76062-e212-47ca-9972-fe91bf43f842">

另外想问下大佬如何实现连续对话？

**Comment by ae86jack** [comment]
谢谢。连续对话功能在规划中，我目前设计方案是用一个单独文件，整个文件就是一个会话，会话是一个block 跟着 一个 block， block 是 ✨💡用户消息 或者 ✨💬 assistant 消息。欢迎提出你的设计方案.

**Comment by miaoziguan** [comment]
> 谢谢。连续对话功能在规划中，我目前设计方案是用一个单独文件，整个文件就是一个会话，会话是一个block 跟着 一个 block， block 是 ✨💡用户消息 或者 ✨💬 assistant 消息。欢迎提出你的设计方案.

<img width="650" alt="image" src="https://github.com/TarsLab/obsidian-ai-zhipu/assets/115944923/e9d97d8a-9686-4573-bae5-8fb3dea6c7c5">
我不是专业人士，但我去询问了一位产品研发专家，他给了我以上回答。至于是否合适，仅供大佬参考。

**Comment by miaoziguan** [comment]
> 谢谢。连续对话功能在规划中，我目前设计方案是用一个单独文件，整个文件就是一个会话，会话是一个block 跟着 一个 block， block 是 ✨💡用户消息 或者 ✨💬 assistant 消息。欢迎提出你的设计方案.

<img width="647" alt="image" src="https://github.com/TarsLab/obsidian-ai-zhipu/assets/115944923/e594deb9-2999-4466-bcef-170006ec0145">


我不是专业人士，但我去询问了一位产品研发专家，他给了我以上回答。至于是否合适，仅供大佬参考。

**Comment by ae86jack** [comment]
@miaoziguan  2.0 新特性:
支持多轮会话，多轮会话的开始标记是连续两行的水平线，例如两行的“---”，结束标记是一行水平线
