### ISSUE TITLE
建议：添加多级扩展列表

### ISSUE THREAD

**Issue by miaoziguan** [TarsLab/obsidian-ai-zhipu#2]
目前的筛选列表只支持2级，但问题也很明显，一旦自定义模版数量过多，筛选成本就会提高，我的想法是支持到3级或者4级扩展，未来会更加方便。

**Comment by ae86jack** [comment]
筛选支持模糊搜索，列表里的顺序也是可以自行调整的。我觉得加多级，可能会导致操作麻烦。

**Comment by miaoziguan** [comment]
> 筛选支持模糊搜索，列表里的顺序也是可以自行调整的。我觉得加多级，可能会导致操作麻烦。

嗯嗯好的，有道理
