### ISSUE TITLE
问题与答案换行

### ISSUE THREAD

**Issue by wardenxyz** [TarsLab/obsidian-ai-zhipu#3]
这是原版：
![图一](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/ac899817-6d6f-488a-834b-e476873e50f2)

红框内问题与答案在同一行，那么它在阅读模式下是这样的：

![图二](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/fab2dde5-cb33-4c3c-aee3-b31279c7c253)
问题与答案会被显示在同一行，不易分辨哪个是问题，哪个是答案

**期望效果**：
![图三](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/4daa984b-5d8a-4ce3-84eb-f8b3ac36fda6)
问题与答案分行显示，易分辨问题与答案，阅读模式下：
![图四](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/4e86f9d3-0e0b-4b7d-8022-723710889fb2)

**感谢开发者开发这个插件，我一直在找支持国内 AI 大模型的插件，今天总算找到了，感谢感谢😘**

**Comment by ae86jack** [comment]
这是个 bug。之前换行用的是单个换行符，现在改用严格的换行模式，两个空格加换行符。我的obsidian配置没有开启严格换行，故一直没发现这个问题，这个问题很影响使用体验。
@MechCrafter  新发布的1.0.4 版本，修复了这个bug。
