### ISSUE TITLE
无论输入什么都会变为 app://obsidian.md 

### ISSUE THREAD

**Issue by wardenxyz** [TarsLab/obsidian-ai-zhipu#7]
![output](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/271b0d9d-4d66-4c63-b134-9c75eb3751ed)
我无论输入什么，选择 “生成内容” 之后就会变成 `app://obsidian.md `

**Comment by wardenxyz** [comment]
obsidian v1.5.12

ai-zhipu v2.0.0

**Comment by wardenxyz** [comment]
![output](https://github.com/TarsLab/obsidian-ai-zhipu/assets/130667961/a3034ca2-29e5-47f0-94ff-5b94f57cb230)

复现步骤如上

**Comment by ae86jack** [comment]
@MechCrafter 谢谢你的反馈，麻烦更新到2.0.1，看看这个bug是否还存在。
